---
opsgenie_api_key: abc123-ffff
alertfile_dir: "/tmp"
target_run_command: '/usr/bin/false'
alert_source: stacybrock
target_script_home: "/tmp"
alert_description: test alert - disregard
alert_message: This is a test of the OpsGenie alert wrapper system
alert_teams:
  - name: itis_sig_stacytesting
    type: team
  - name: foobar
    type: user

